### ISSUE TITLE
DataCollection: Holothuria Tubulosa

### ISSUE THREAD

**Issue by ahlekses** [2023-ITD109-ITB/Web-App-MLIM_Seacucumber-LC#1]

**Comment by Danelleme23** [comment]
https://drive.google.com/drive/folders/1ubaIub2uDddQitXe8W7ax_u_Nt961o3i

**Comment by benchdagr8** [comment]
https://drive.google.com/drive/folders/1xT5t_BHiDcrRi-dVUyyBVAxDzU6m0KiA
