### ISSUE TITLE
DataCollection: Royal Cucumber

### ISSUE THREAD

**Issue by ahlekses** [2023-ITD109-ITB/Web-App-MLIM_Seacucumber-LC#2]

**Comment by Damaulao** [comment]
https://drive.google.com/drive/folders/1ziLa1MTnDOv29vW4N7uH7D5_wAGeWZ9S

**Comment by MMarkAAnthony** [comment]
https://drive.google.com/drive/folders/1I056AdUQEkrcizo9xsjEnM-2j2NLmEip

**Comment by syntaxboybe** [comment]
GDrive Link(#image_data_collected): https://drive.google.com/drive/u/1/folders/1BrxiTxtxPJHHtcIoWvHsXzKNqp5MM82f
