### ISSUE TITLE
DataCollection: Apotichupus janponicus

### ISSUE THREAD

**Issue by ahlekses** [2023-ITD109-ITB/Web-App-MLIM_Seacucumber-LC#3]

**Comment by wennneth** [comment]
[https://drive.google.com/drive/folders/16smFwF1r8Ou4pVjsSqkppNZfi-IwMwwM?usp=drive_link]

**Comment by wennneth** [comment]
https://drive.google.com/drive/folders/16smFwF1r8Ou4pVjsSqkppNZfi-IwMwwM?usp=sharing

**Comment by velasco-dianne** [comment]
https://drive.google.com/drive/folders/17VoIOSSeB_US79xX4Q-EmU_fXQzud1Fl?usp=drive_link
