### ISSUE TITLE
DataCollection: Holothuria Atra

### ISSUE THREAD

**Issue by ahlekses** [2023-ITD109-ITB/Web-App-MLIM_Seacucumber-LC#4]

**Comment by DicenRizza** [comment]
[Holothuria-Atra-Classification-20231114T012622Z-001.zip](https://github.com/2023-ITD109-ITB/MLIM-SeaCucumber/files/13343563/Holothuria-Atra-Classification-20231114T012622Z-001.zip)

**Comment by DeesayCube** [comment]
https://drive.google.com/drive/folders/1Me_v5gWp3wx_zwDBT7Z5g11G9pc37F7X?usp=drive_link

**Comment by DicenRizza** [comment]
https://drive.google.com/drive/folders/1KLHsd1ORjV-r97fWBF1UjfPiGYAAfCRC?usp=drive_link
