### ISSUE TITLE
DataCollection: Holothuria Scabra

### ISSUE THREAD

**Issue by ahlekses** [2023-ITD109-ITB/Web-App-MLIM_Seacucumber-LC#5]

**Comment by jayabels23** [comment]
https://drive.google.com/drive/folders/1tLg1QQrjMh4xZ1jRULA3SRYcenfoEEf9

**Comment by imchermia** [comment]
https://drive.google.com/drive/folders/1tLg1QQrjMh4xZ1jRULA3SRYcenfoEEf9?usp=drive_link

**Comment by bebyana** [comment]
https://drive.google.com/drive/folders/1tLg1QQrjMh4xZ1jRULA3SRYcenfoEEf9?usp=drive_link
